"""Helpers for redispatching validated payloads through FastAPI."""

from __future__ import annotations

import asyncio
import logging
import types
import typing as t
from collections import abc

import fastapi
import pydantic

from fastapi_patterns import utilities

if t.TYPE_CHECKING:
    import starlette.types

    from fastapi_patterns import lifespan


class DispatchState:
    def __init__(self, app: fastapi.FastAPI) -> None:
        self.active_tasks: set[asyncio.Task[None]] = set()
        self.app = app
        self.logger = logging.getLogger(__package__).getChild('DispatchState')

    def schedule_request(
        self,
        task_name: str,
        receive_message: starlette.types.Receive,
        scope: starlette.types.Scope,
    ) -> asyncio.Task[None]:
        self.logger.info(
            'scheduling task %r for scope %r',
            task_name,
            {
                'type': scope['type'],
                'path': scope['path'],
                'root_path': scope['root_path'],
                'method': scope['method'],
            },
        )

        task = asyncio.create_task(
            self.app(scope, receive_message, _blackhole_send), name=task_name
        )
        self.active_tasks.add(task)
        task.add_done_callback(self._task_finished)

        return task

    def _task_finished(self, task: asyncio.Task[None]) -> None:
        task_name = utilities.get_task_name(task)
        try:
            if task.cancelled():
                self.logger.warning('task %r cancelled', task_name)
            elif exc := task.exception():
                self.logger.error(
                    'task %r failed',
                    task_name,
                    exc_info=(type(exc), exc, exc.__traceback__),
                )
            else:
                self.logger.info('task %r finished', task_name)
        finally:
            self.active_tasks.discard(task)

    async def __aenter__(self) -> DispatchState:
        return self

    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        exc_traceback: types.TracebackType | None,
    ) -> object:
        for task in self.active_tasks:
            task.cancel()
        await asyncio.gather(*self.active_tasks, return_exceptions=True)
        return None  # propagate exception


type DispatchMessage = t.Callable[[str, str, pydantic.BaseModel], None]


def _get_dispatch_task_runner(
    request: fastapi.Request, lifespan_map: lifespan.LifespanMap
) -> DispatchMessage:
    def dispatch_message(
        task_name: str, path: str, payload: pydantic.BaseModel
    ) -> None:
        body = payload.model_dump_json().encode()
        parent_state = t.cast(
            'abc.Mapping[str, t.Any]', request.scope.get('state', {})
        )
        scope: starlette.types.Scope = {
            'type': 'http',
            'asgi': {'version': '3.0'},
            'http_version': '1.1',
            'method': 'POST',
            'path': path,
            'raw_path': path.encode(),
            'query_string': b'',
            'headers': [
                (b'content-length', str(len(body)).encode()),
                (b'content-type', b'application/json'),
                *[
                    (k.lower().encode(), v.encode())
                    for k, v in request.headers.items()
                    if k.lower() not in ('content-length', 'content-type')
                ],
            ],
            'client': ('internal', 0),
            'server': ('internal', 0),
            'scheme': 'http',
            'root_path': '',
            'app': request.app,
            'state': dict(parent_state),
        }

        async def receive_message() -> starlette.types.Message:
            return {'type': 'http.request', 'body': body, 'more_body': False}

        state = lifespan_map.get_state(DispatchState)
        state.schedule_request(task_name, receive_message, scope)

    return dispatch_message


DispatchTaskRunner = t.Annotated[
    DispatchMessage, fastapi.Depends(_get_dispatch_task_runner)
]


async def _blackhole_send(_message: starlette.types.Message) -> None:
    """Discard the synthetic response generated by the internal request."""
